language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements-tests.txt

# command to run tests
script: 
  - coverage run package/setup.py test

after_success:
  - coveralls
